### ISSUE TITLE
FSUSER error 0xC92044E6 when writing bgm-data

### ISSUE THREAD

**Issue by yellows8** [yellows8/3ds_homemenu_extdatatool#3]
Multiple users apparently get the error in the title, when writing the bgm-data to extdata. I reproduced this with a theme one user was attempting to install. This results in all but the bgm being written correctly.

The cause of this is unknown.

**Comment by yellows8** [comment]
BGM writing only works correctly when the extdata file for it isn't already open: that is, Home Menu isn't already using a theme from theme-cache with BGM.

**Comment by leo60228** [comment]
How do I fix this?

**Comment by yellows8** [comment]
In Home Menu theme-settings, set the selected theme to the default. Then run this tool again.

**Comment by leo60228** [comment]
Then I get no theme.

**Comment by yellows8** [comment]
"run this tool again" == use the "Enable persistent theme-cache" and "Copy theme-data from sd to extdata" options.

**Comment by leo60228** [comment]
Thanks!
